// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ61OYxyggrCDMZHJKAAz-kNPomcB871c',
    appId: '1:136297605897:web:60ff28990e5087856581d8',
    messagingSenderId: '136297605897',
    projectId: 'mynotes-mr-ducky-pilot',
    authDomain: 'mynotes-mr-ducky-pilot.firebaseapp.com',
    storageBucket: 'mynotes-mr-ducky-pilot.appspot.com',
    measurementId: 'G-7CCFFTHN3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqg8x2ReZGfGDgRtrOa9-V4vy9RAPOtmI',
    appId: '1:136297605897:android:3c76d0d27c67283e6581d8',
    messagingSenderId: '136297605897',
    projectId: 'mynotes-mr-ducky-pilot',
    storageBucket: 'mynotes-mr-ducky-pilot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuDXqU6OrtH8dBsU7K-zD8XcTPeslTahs',
    appId: '1:136297605897:ios:62a40cb0c7edba576581d8',
    messagingSenderId: '136297605897',
    projectId: 'mynotes-mr-ducky-pilot',
    storageBucket: 'mynotes-mr-ducky-pilot.appspot.com',
    iosBundleId: 'com.mrduckypilot.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuDXqU6OrtH8dBsU7K-zD8XcTPeslTahs',
    appId: '1:136297605897:ios:d529639842d797d26581d8',
    messagingSenderId: '136297605897',
    projectId: 'mynotes-mr-ducky-pilot',
    storageBucket: 'mynotes-mr-ducky-pilot.appspot.com',
    iosBundleId: 'com.mrduckypilot.mynotes.RunnerTests',
  );
}
